var greet = require('./greet2').greet;
var greet3 = require('./greet3');
var Greet4 = require('./greet4');
var greet5 = require('./greet5');
console.log(greet3);
greet();
greet3.greet();
var grtr = new Greet4();
grtr.greet();
greet5.greet();
